const lepik = require("../index.js")

async function main() {
  lepik.getMousePosition().then(e => console.log(`Should print mousePosition: x:${e.x} y:${e.y}`))
  await sleep(1000)
  console.log("Should click the left mouse")
  lepik.mouseClick("left")
  await sleep(100)
  console.log("Should click the right mouse")
  lepik.mouseClick("right")
  await sleep(100)
  console.log("Should click the middle mouse")
  lepik.mouseClick("middle")
  await sleep(1000)
  console.log("Should do mouseScroll up")
  lepik.mouseScroll(10)
  await sleep(100)
  console.log("Should do mouseScroll down")
  lepik.mouseScroll(-10)
  await sleep(1000)
  console.log("Should drag mouse")
  lepik.mouseDrag(0, 0, 100, 100)
  await sleep(1000)
  console.log("Should move mouse")
  lepik.mouseMove(100, 100)
  await sleep(1000)
  console.log("Should press a")
  lepik.keyTap("a")
  await sleep(1000)
  console.log("Should write abcdefg")
  lepik.write("abcdefg")
  await sleep(1000)
  lepik.close()
}
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
main()
