const lepik = require("../index.js")

async function main() {
  lepik.getScreenSize().then(e => console.log(`Should print screenSize: width:${e.width} height:${e.height}`))
  await lepik.delay(1000)
  lepik.getMousePosition().then(e => console.log(`Should print mousePosition: x:${e.x} y:${e.y}`))
  await lepik.delay(1000)
  console.log("Should click the left mouse")
  lepik.mouseClick("left")
  await lepik.delay(100)
  console.log("Should click the right mouse")
  lepik.mouseClick("right")
  await lepik.delay(100)
  console.log("Should click the middle mouse")
  lepik.mouseClick("middle")
  await lepik.delay(1000)
  console.log("Should do mouseScroll up")
  lepik.mouseScroll(10)
  await lepik.delay(100)
  console.log("Should do mouseScroll down")
  lepik.mouseScroll(-10)
  await lepik.delay(1000)
  console.log("Should drag mouse")
  lepik.mouseDrag(0, 0, 100, 100)
  await lepik.delay(1000)
  console.log("Should move mouse")
  lepik.mouseMove(1000, 1000)
  await lepik.delay(1000)
  console.log("Should press a")
  lepik.keyTap("a")
  await lepik.delay(1000)
  console.log("Should write abcdefg")
  lepik.write("abcdefg")
  await lepik.delay(1000)
  lepik.close()
}

main()

